# Generated by Django 5.2.5 on 2025-09-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_created_at_transfer_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='user',
            new_name='owner',
        ),
    ]
