# Generated by Django 5.2.5 on 2025-09-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_user_transfer_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-date']},
        ),
    ]
